{% set version = "4.12.0.20250204" %}

package:
  name: types-beautifulsoup4
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/t/types-beautifulsoup4/types_beautifulsoup4-{{ version }}.tar.gz
    sha256: f083d8edcbd01279f8c3995b56cfff2d01f1bb894c3b502ba118d36fbbc495bf
  - url: https://raw.githubusercontent.com/python/typeshed/main/LICENSE
    sha256: 295f8538c94ae5c3043301cf7cff1c852dab6a786a8ddee471e061b40d5ecabe

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - types-html5lib

test:
  commands:
    - pip check
    - test -f $SP_DIR/bs4-stubs/__init__.pyi                 # [unix]
    - if not exist %SP_DIR%\\bs4-stubs\\__init__.pyi exit 1  # [win]
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for beautifulsoup4
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/mypy
