{% set version = "4.12.0.20240106" %}

package:
  name: types-beautifulsoup4
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/t/types-beautifulsoup4/types-beautifulsoup4-{{ version }}.tar.gz
    sha256: 98d628985b71b140bd3bc22a8cb0ab603c2f2d08f20d37925965eb4a21739be8
  - url: https://raw.githubusercontent.com/python/typeshed/main/LICENSE
    sha256: 295f8538c94ae5c3043301cf7cff1c852dab6a786a8ddee471e061b40d5ecabe

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - types-html5lib

test:
  commands:
    - pip check
    - test -f $SP_DIR/bs4-stubs/__init__.pyi                 # [unix]
    - if not exist %SP_DIR%\\bs4-stubs\\__init__.pyi exit 1  # [win]
  requires:
    - pip

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for beautifulsoup4
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/mypy
